### ISSUE TITLE
Neither game, simulation and animation working

### ISSUE THREAD

**Issue by remimimimimi** [ECburx/IdrisGL#1]
I try to run samples but them doesn't rerender on the new frame. Suppose that problem is somewhere in display because in the 2048 sample I hear sound when pressing arrows.

**Comment by ECburx** [comment]
Thanks. Could you provide your OS info, Idris version and anything else that might be helpful to me?

**Comment by algebraic-dev** [comment]
I'm having the same problems. Info:
Arch Linux x86_64 5.16.3-arch1-1 

All dependencies installed from arch linux repo:

     sdl2        2.0.20-1
     sdl2_gfx    1:1.0.4-2
     sdl2_image  2.0.5-2
     sdl2_mixer  2.0.4-7
     sdl2_ttf    2.0.18-1

**Comment by ECburx** [comment]
Thank you all for the issue. It is relating to the primitive types on Idris2 V0.5.1 and has been fixed.
