### ISSUE TITLE
Problem compiling with idris2 v0.6.0.

### ISSUE THREAD

**Issue by domandlj** [ECburx/IdrisGL#3]
The project doesn't compile with `Idris2 v0.6.0`.

There is an indentation problem with the `mutual` keyword, is easy to fix, just change the ocurrences of

```idris
where mutual  
     ...
```
to 
```idris
where 
   mutual  
     ...
```
Take a look at the changes of the new version of Idris in [link](https://github.com/idris-lang/Idris2/blob/102d7ebc18a9e881021ed4b05186cccda5274cbe/CHANGELOG.md)

Awesome project btw.

**Comment by ECburx** [comment]
Brilliant thanks for finding the issue and possible solution.

**Comment by domandlj** [comment]
It's an awesome project, hope you continue maintaining it. I'm on OSX and there are some problems with the libraries used, so if i manage to get it wright i can comment on the solution. But it would have to be after i finish my exams haha. Greetings from Argentina.
