### ISSUE TITLE
Adding idrisgl to pack

### ISSUE THREAD

**Issue by GunpowderGuy** [ECburx/IdrisGL#4]
Pack has become the de facto package manager for idris2, could someone add this library to their database collection?

**Comment by GunpowderGuy** [comment]
@ECburx would this be too hard?

**Comment by ECburx** [comment]
> @ECburx would this be too hard?

Sorry, I was too busy last week. Will look into that.

**Comment by ECburx** [comment]
You can now install idrisGL using Pack.
Thanks for the advice.
